### PR TITLE
Correct typo, AppSearch -> App Search

### PR DESCRIPTION
**Pull request by richkuz**
Trivial change to fix capitalization of App Search in a heading.

### CODE REVIEW

**Comment by richkuz** [comment]
@jsvd would you be willing to review and merge this small doc change? Also, I am not sure how to fix the CI failure.

**Comment by jsvd** [comment]
@andsel since we moved this to an integration plugin, can you fix it this typo there instead (and see if there are other instances of the same typo?

**Comment by andsel** [comment]
@jsvd fixes ported to the integration plugin https://github.com/logstash-plugins/logstash-integration-elastic_enterprise_search/pull/9
@richkuz the fail on 8.0.0-SNAPSHOT is something "expected" because EnterpriseSearch 8.0.0 is a link to the latest `7.x` and the EnterpriseSearch `7.x` expects to work with Elasticsearch `7.x`

**Comment by richkuz** [comment]
Thanks! I'll close this PR then in favor of the more comprehensive PR opened in the integration plugin, https://github.com/logstash-plugins/logstash-integration-elastic_enterprise_search/pull/9

**Pull request closed without merging**
